export const SCAFFOLDS = [
  {
    label: "Assembler", filename: "assemble.py",
    blurb: "Drop this beside your prompt code. Slots are typed collections; a versioned profile decides the order; the fitting step protects, compresses, drops, or refuses.",
    text: [
      "# Context Window Architecture — assembly scaffold",
      "# Slots hold items. A profile renders them. Empty slots are omitted, never emitted.",
      "",
      "PROFILE = load_profile('policy-first-chat/v1')   # per route, versioned, evaluated",
      "",
      "def assemble_context(req, profile=PROFILE):",
      "    items = [",
      "        *slot('governance.instructions',    [policy(req.route)],            authority='governing'),",
      "        *slot('governance.capabilities',    tool_specs(req.allowed),        authority='capability'),",
      "        *slot('governance.output_contract', [OUTPUT_CONTRACT],              authority='governing'),",
      "        *slot('state.user',                 user_facts(req.user),           authority='state'),",
      "        *slot('state.task',                 [req.task.snapshot()],          authority='state'),",
      "        *slot('evidence.knowledge',         retrieve(req.query, k=12),      authority='reference'),",
      "        *slot('evidence.tool_results',      req.observations,               authority='observation'),",
      "        *slot('interaction.memory',         memory.summaries(req.session),  authority='generated'),",
      "        *slot('interaction.history',        req.session.recent(turns=6),    authority='user'),",
      "        *slot('interaction.examples',       examples_for(req.route),        authority='steering'),",
      "        *slot('interaction.query',          [req.message],                  authority='user'),",
      "    ]",
      "    admitted  = admit(items, req)                    # scope, eligibility, freshness, trust",
      "    resolved  = resolve_conflicts(admitted)          # authority + freshness matrix",
      "    fitted    = fit(resolved, budget=req.budget)     # reserve output; protect; compress; drop; or refuse",
      "    payload   = profile.render(fitted)               # placement belongs to the profile, not the slot",
      "    trace     = Trace(profile, items, admitted, fitted)",
      "    return payload, trace",
      "",
      "def slot(name, bodies, authority):",
      "    return [Item(slot=name, body=b, authority=authority, **provenance(b)) for b in bodies if b]",
      "",
      "PROTECTED    = {'governance.instructions', 'state.task', 'governance.output_contract', 'interaction.query'}",
      "COMPRESSIBLE = ['interaction.memory', 'interaction.history', 'evidence.knowledge', 'evidence.tool_results']",
      "DROPPABLE    = ['interaction.examples', 'state.user']",
      "",
      "def fit(items, budget):",
      "    budget -= RESERVED_OUTPUT",
      "    for name in DROPPABLE:                            # 1. drop redundant steering and low-value facts",
      "        if total(items) <= budget: break",
      "        items = [i for i in items if i.slot != name]",
      "    for name in COMPRESSIBLE:                         # 2. compress with source links, never blind truncation",
      "        if total(items) <= budget: break",
      "        items = [i.compress() if i.slot == name else i for i in items]",
      "    if total(items) > budget:                         # 3. essential evidence does not fit",
      "        raise ContextRefused('retrieve narrower, summarise with traceability, or route for more context')",
      "    return items"
    ].join("\n")
  },
  {
    label: "Payload", filename: "payload.txt",
    blurb: "The wire format, empty, in the default profile's order. Tag however your stack prefers — what matters is that every item names its slot and authority.",
    text: [
      "<!-- profile: policy-first-chat/v1 -->",
      "",
      "<!-- governance.instructions · authority=governing · protected -->",
      "<instructions version=\"\"></instructions>",
      "",
      "<!-- state.user · authority=state · scope=user,session -->",
      "<user_facts></user_facts>",
      "",
      "<!-- evidence.knowledge · authority=reference · one <evidence> per packet -->",
      "<evidence id=\"\" source=\"\" version=\"\" trust=\"\" as_of=\"\"></evidence>",
      "",
      "<!-- state.task · authority=state · app-owned, canonical -->",
      "<task></task>",
      "",
      "<!-- interaction.memory · authority=generated · lineage=summary · ttl -->",
      "<memory></memory>",
      "",
      "<!-- interaction.history · authority=user · verbatim, bounded -->",
      "<history></history>",
      "",
      "<!-- governance.capabilities · authority=capability -->",
      "<tools></tools>",
      "",
      "<!-- evidence.tool_results · authority=observation · one <observation> per call -->",
      "<observation call=\"\" age=\"\"></observation>",
      "",
      "<!-- interaction.examples · authority=steering · droppable -->",
      "<examples></examples>",
      "",
      "<!-- governance.output_contract · authority=governing · protected -->",
      "<format></format>",
      "",
      "<!-- interaction.query · authority=user · protected -->",
      "<query></query>",
      "",
      "<!-- trace: <id> · included/compressed/excluded counts · conflicts -->"
    ].join("\n")
  },
  {
    label: "Item schema", filename: "context_item.yaml",
    blurb: "What every item carries beyond its slot. Without these fields a fixed order still produces unpredictable payloads.",
    text: [
      "context_item:",
      "  id: \"retrieval:refunds-eu:v17#p4\"",
      "  slot: evidence.knowledge",
      "  type: evidence                       # governing | state | evidence | observation | memory | steering | trigger",
      "  source: policy-corpus",
      "  source_version: \"2026-09-10\"",
      "  authority: reference_only            # governing | user | state | reference_only | observation | generated | untrusted",
      "  trust: verified                      # verified | unverified | untrusted",
      "  freshness: \"2026-09-12T15:30:00Z\"",
      "  expires: \"2026-12-12T15:30:00Z\"",
      "  scope: refund_request                # tenant / user / session / task / locale / step",
      "  eligibility: \"similarity >= 0.82 AND jurisdiction == EU\"",
      "  token_budget: 420",
      "  tier: compressible                   # protected | compressible | droppable",
      "  compression: extractive_quote",
      "  conflict_policy: defer_to_current_tool_result",
      "  injection_risk: untrusted_content",
      "  lineage: verbatim                    # verbatim | summarised | redacted | translated | extracted | generated",
      "  placement: evidence_near_query       # hint consumed by the profile, not a fixed position"
    ].join("\n")
  },
  {
    label: "JSON Schema", filename: "context_item.schema.json",
    blurb: "The item schema as data: the same fields and enums as context_item.yaml, plus body. Validate what your producers emit before the assembler sees it.",
    text: [
     
      "{",
      "  \"$schema\": \"https://json-schema.org/draft/2020-12/schema\",",
      "  \"$id\": \"https://contextwindowarchitecture.io/schema/context_item.schema.json\",",
      "  \"title\": \"CWA context item\",",
      "  \"description\": \"One governed object in a slot. Fields match context_item.yaml. Wire syntax is not specified; fields are.\",",
      "  \"type\": \"object\",",
      "  \"additionalProperties\": false,",
      "  \"required\": [",
      "    \"id\",",
      "    \"slot\",",
      "    \"source\",",
      "    \"source_version\",",
      "    \"authority\",",
      "    \"trust\",",
      "    \"freshness\",",
      "    \"body\"",
      "  ],",
      "  \"properties\": {",
      "    \"id\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"Stable, provenance-bearing id, e.g. retrieval:refunds-eu:v17#p4\"",
      "    },",
      "    \"slot\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"governance.instructions\",",
      "        \"governance.capabilities\",",
      "        \"governance.output_contract\",",
      "        \"state.user\",",
      "        \"state.task\",",
      "        \"evidence.knowledge\",",
      "        \"evidence.tool_results\",",
      "        \"interaction.memory\",",
      "        \"interaction.history\",",
      "        \"interaction.examples\",",
      "        \"interaction.query\"",
      "      ]",
      "    },",
      "    \"type\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"governing\",",
      "        \"state\",",
      "        \"evidence\",",
      "        \"observation\",",
      "        \"memory\",",
      "        \"steering\",",
      "        \"trigger\"",
      "      ]",
      "    },",
      "    \"source\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"Document, turn, tool call, database field, or memory write it came from\"",
      "    },",
      "    \"source_version\": {",
      "      \"type\": \"string\"",
      "    },",
      "    \"authority\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"governing\",",
      "        \"user\",",
      "        \"state\",",
      "        \"reference_only\",",
      "        \"observation\",",
      "        \"generated\",",
      "        \"untrusted\"",
      "      ]",
      "    },",
      "    \"trust\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"verified\",",
      "        \"unverified\",",
      "        \"untrusted\"",
      "      ]",
      "    },",
      "    \"freshness\": {",
      "      \"type\": \"string\",",
      "      \"format\": \"date-time\",",
      "      \"description\": \"When it was true (as_of)\"",
      "    },",
      "    \"expires\": {",
      "      \"type\": \"string\",",
      "      \"format\": \"date-time\",",
      "      \"description\": \"When it must be revalidated; expired items are excluded, not aged silently\"",
      "    },",
      "    \"scope\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"tenant / user / session / task / locale / step\"",
      "    },",
      "    \"eligibility\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"The deterministic rule that admitted it, stated so a test can replay it\"",
      "    },",
      "    \"token_budget\": {",
      "      \"type\": \"integer\",",
      "      \"minimum\": 0",
      "    },",
      "    \"tier\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"protected\",",
      "        \"compressible\",",
      "        \"droppable\"",
      "      ]",
      "    },",
      "    \"compression\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"Precomputed variant to use under budget pressure, e.g. extractive_quote\"",
      "    },",
      "    \"conflict_policy\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"What wins if another item disagrees, e.g. defer_to_current_tool_result\"",
      "    },",
      "    \"injection_risk\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"none\",",
      "        \"untrusted_content\"",
      "      ]",
      "    },",
      "    \"lineage\": {",
      "      \"type\": \"string\",",
      "      \"enum\": [",
      "        \"verbatim\",",
      "        \"summarised\",",
      "        \"redacted\",",
      "        \"translated\",",
      "        \"extracted\",",
      "        \"generated\"",
      "      ]",
      "    },",
      "    \"placement\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"Hint consumed by the profile, not a fixed position, e.g. evidence_near_query\"",
      "    },",
      "    \"body\": {",
      "      \"type\": \"string\",",
      "      \"description\": \"The content rendered into the payload\"",
      "    }",
      "  }",
      "}"

    ].join("\n")
  },
  {
    label: "For agents", filename: "cwa.md",
    blurb: "Put this in your repo so coding agents assemble context the same way your team does.",
    text: [
      "# Context Window Architecture (CWA)",
      "",
      "Assemble every LLM payload from typed slots grouped in four planes.",
      "Each slot holds zero or more items. Omit empty slots. A versioned profile",
      "decides serialization order per route. Every assembly run emits a trace.",
      "",
      "## Planes and slots",
      "",
      "| Plane       | Slot                       | Holds                                   | Authority     | Tier         |",
      "| ----------- | -------------------------- | --------------------------------------- | ------------- | ------------ |",
      "| Governance  | governance.instructions    | Identity, rules, refusals, safety       | governing     | protected    |",
      "| Governance  | governance.capabilities    | Permitted tools and their contracts     | capability    | protected    |",
      "| Governance  | governance.output_contract | Required structure, style, schema       | governing     | protected    |",
      "| State       | state.user                 | Profile, entitlements, locale, prefs    | state         | droppable    |",
      "| State       | state.task                 | Canonical workflow state, app-owned     | state         | protected    |",
      "| Evidence    | evidence.knowledge         | Retrieved packets with provenance       | reference     | compressible |",
      "| Evidence    | evidence.tool_results      | Tool observations, with age             | observation   | compressible |",
      "| Interaction | interaction.memory         | Summaries and inferences, with TTL      | generated     | compressible |",
      "| Interaction | interaction.history        | Verbatim recent turns, bounded          | user          | compressible |",
      "| Interaction | interaction.examples       | Steering pairs, ranked by similarity    | steering      | droppable    |",
      "| Interaction | interaction.query          | The unprocessed live request            | user          | protected    |",
      "",
      "## Rules",
      "",
      "1. Language guidance goes in context. Enforceable invariants go in code, tool guards, or a policy engine.",
      "2. Slots never override platform roles or application controls. Untrusted content never enters a governance slot.",
      "3. State is canonical and application-owned. Memory is fallible, source-linked, expiring, revocable.",
      "4. Evidence is admitted through a pipeline (rewrite, retrieve, rerank, dedupe, filter, packetize, budget, attribute). An empty result is a recorded outcome, not a silent answer.",
      "5. Conflicts resolve by authority, then freshness: policy > user > state > observation > reference > memory. Conflicting sources are surfaced or escalated, never silently picked.",
      "6. Fitting: reserve output tokens; keep protected slots intact; drop droppable; compress compressible with source links; if essential evidence still does not fit, refuse and route.",
      "7. Placement is a profile, versioned per route and evaluated. Never assume one order is optimal for every model.",
      "8. Every assembly run emits a trace: profile, budget, included, compressed, excluded (with reasons), conflicts.",
      "",
      "## Determinism claim",
      "",
      "Given the same request state, source versions, selection rules, and budget, the assembler emits the same",
      "payload in the same order. CWA makes no claim about the determinism of the model's output.",
      "",
      "Reference: https://contextwindowarchitecture.io"
    ].join("\n")
  }
];
